defaults: &defaults
  adapter:  postgresql
  pool:     5
  timeout:  5000
  host:     localhost

development:
  <<:       *defaults
  username: marius
  password:
  database: ember_api_dev

test:
  <<:       *defaults
  username: marius
  password:
  database: ember_api_test

production:
  <<:       *defaults
  username: postgres
  password:
  database: ember_api_prod
